require('dotenv').config();
const express = require('express');
const nodemailer = require('nodemailer');
const multer = require('multer');
const bodyParser = require('body-parser');

const app = express();
const router = express.Router();

// Middleware to parse JSON body
app.use(bodyParser.json());

// Set up the transport using your SMTP server
const transporter = nodemailer.createTransport({
  host: 'smtp.hostinger.com',
  port: 465,
  secure: true, // true for 465, false for other ports
  auth: {
    user: process.env.EMAIL_USER, // Your email address
    pass: process.env.EMAIL_PASS, // Your email password or app password
  },
});

router.post('/getintouch', async (req, res) => {
  const { user_name, user_email, user_phone, user_country } = req.body;

  // Email sent to you (admin)
  const mailOptions = {
    from: `"CloudSentrics Get In Touch Form" <${process.env.EMAIL_USER}>`,
    to: process.env.EMAIL_USER,
    subject: '📨 New Get In Touch Submission',
    html: `
      <div style="font-family: Arial, sans-serif; padding: 20px; max-width: 600px; margin: auto; color: #333;">
        <div style="text-align: center;">
          <img src="https://cloudsentrics.org/assets/logo.jpg" alt="CloudSentrics Logo" style="width: 120px; margin-bottom: 20px;" />
        </div>
        <h2 style="color: #333;">📬 You've Got a New Message</h2>
        <p style="font-size: 16px;">Someone just filled out the <strong>Get In Touch</strong> form.</p>
        <div style="margin-top: 20px; font-size: 16px;">
          <p><strong>👤 Full Name:</strong> ${user_name}</p>
          <p><strong>📧 Email:</strong> ${user_email}</p>
          <p><strong>📱 Phone:</strong> ${user_phone || 'N/A'}</p>
          <p><strong>🌍 Country:</strong> ${user_country || 'N/A'}</p>
        </div>
        <hr style="margin: 30px 0;">
        <p style="font-size: 12px; color: #999;">
          This message was submitted via the Get In Touch form on CloudSentrics.org.
        </p>
      </div>
    `,
  };

  // Email sent to the user
  const userMailOptions = {
    from: `"CloudSentrics" <${process.env.EMAIL_USER}>`,
    to: user_email,
    subject: '✅ We’ve received your message!',
    html: `
      <div style="font-family: Arial, sans-serif; padding: 20px; max-width: 600px; margin: auto; color: #333;">
        <div style="text-align: center;">
          <img src="https://cloudsentrics.org/assets/logo.jpg" alt="CloudSentrics Logo" style="width: 120px; margin-bottom: 20px;" />
        </div>
        <h2 style="color: #333;">Thanks for reaching out, ${user_name}!</h2>
        <p style="font-size: 16px;">
          We’ve received your message and one of our team members will get back to you shortly.
        </p>
        <p style="font-size: 16px;">Here’s a quick summary of what you submitted:</p>
        <div style="margin-top: 15px; font-size: 16px;">
          <p><strong>📧 Email:</strong> ${user_email}</p>
          <p><strong>📱 Phone:</strong> ${user_phone || 'N/A'}</p>
          <p><strong>🌍 Country:</strong> ${user_country || 'N/A'}</p>
        </div>
        <hr style="margin: 30px 0;">
        <p style="font-size: 12px; color: #999;">
          This message was auto-generated by CloudSentrics.org. Thank you for choosing us!
        </p>
      </div>
    `,
  };

  try {
    // Send both emails in parallel
    await Promise.all([
      transporter.sendMail(mailOptions),
      transporter.sendMail(userMailOptions),
    ]);

    res.status(200).json({
      success: true,
      message: 'Contact message sent successfully to both admin and user',
    });
  } catch (error) {
    console.error('❌ Error sending email:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to send contact message',
      error: error.message,
    });
  }
});

module.exports = router;